language: node_js
node_js:
  - 14


jobs:
  include:
    - stage: lint
      name: 'Lint'
      script: 'npm run lint:client && npm run lint:server'
    - stage: test
      name: 'Unit Tests'
      script: 'npm run test'
    - stage: build
      name: 'Build'
      script: 'npm run build'
    - stage: deploy
      script: 'npm run build'
      name: 'Deploy to Heroku'
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: ancient-reef-96943
        skip_cleanup: true
        on:
          branch: main
